redis:
  uri: http://localhost:6379/
aws:
  access_key_id: OVERRIDE_ME
  secret_access_key: OVERRIDE_ME
hasher:
  secret_key: OVERRIDE_ME
google_analytics:
  analytics_id: UA-31572927-1
email:
  from_address: Szelena Gray <info@rootstriker.org>
  domain: rootstrikers.org
action_kit:
   host: <%= ENV["AK_IMPORT_DB_HOST"] %>
   username: <%= ENV["AK_IMPORT_DB_UNAME"] %>
   password: <%= ENV["AK_IMPORT_DB_PWD"] %>
   database: <%= ENV["AK_IMPORT_DB"] %>
cloudmailin:
  token: <%= ENV["CLOUDMAILIN_TOKEN"] %>
organization:
  name: "Rootstrikers"
  email: "info@rootstrikers.org"
  unsubscribe_url: "https://act.demandprogress.org/unsubscribe/unsubscribe?source=watchdog"
  logo: 'logo.png'
site:
  name: "Rootstrikers.org"
  email: "support@rootstrikers.org"
  hostname: "act.rootstrikers.org"
  feedback_email: info+watchdog@demandprogress.org
  list_unsubscribe: "unsubscribe@appmail.rootstrikers.org"
