redis:
    uri: <%= ENV["REDISTOGO_URL"] %>
aws:
   access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
   secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
hasher:
   secret_key: <%= ENV["HASHER_SECRET_KEY"] %>
google_analytics:
   analytics_id: <%= ENV["ANALYTICS_ID"] %>
   oauth:
     user_id: <%= ENV["OAUTH_USER_ID"] %>
     client_secret: <%= ENV["OAUTH_CLIENT_SECRET"] %>
     token: <%= ENV["OAUTH_TOKEN"] %>
     secret: <%= ENV["OAUTH_SECRET"] %>
